title: YOUNG-JIN NA
description: Note what I study
baseurl: "" # the subpath of your site, e.g. /blog
url: "devyoungjin.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Rahul & Rishabh Jain
author-image:   profile.jpg
author-job: Junior Developer
author-email: devyjna@gmail.com   # Add your email for contant form.
author-twitter: # Add your twitter account
about-author:  I am a Junior developer focusing on AI, especially Computer Vision and Audio AI. 

# Social settings
social-twitter:
social-facebook:
social-github:    devyoungjin
social-pinterest:
social-instagram: iamyoungjin
social-youtube:
social-vk:
social-linkedin: youngjin-na-a43302234/

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: UA-167034495-1 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
